openapi: 3.0.0
info:
  title: Language Learning Portal API
  version: 1.0.0
  description: |
    API for language learning portal that serves as:
    - Vocabulary inventory
    - Learning Record Store (LRS)
    - Unified learning app launchpad

servers:
  - url: /api

components:
  schemas:
    Word:
      type: object
      required:
        - japanese
        - romaji
        - english
        - parts
      properties:
        id:
          type: integer
        japanese:
          type: string
          example: "こんにちは"
        romaji:
          type: string
          example: "konnichiwa"
        english:
          type: string
          example: "hello"
        parts:
          type: object
          description: JSON object containing word components
        correct_count:
          type: integer
          example: 5
        wrong_count:
          type: integer
          example: 2

    WordDetail:
      allOf:
        - $ref: '#/components/schemas/Word'
        - type: object
          properties:
            stats:
              type: object
              properties:
                correct_count:
                  type: integer
                wrong_count:
                  type: integer
            groups:
              type: array
              items:
                $ref: '#/components/schemas/Group'

    Group:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
        name:
          type: string
          example: "Basic Greetings"
        word_count:
          type: integer
          example: 20

    GroupDetail:
      allOf:
        - $ref: '#/components/schemas/Group'
        - type: object
          properties:
            stats:
              type: object
              properties:
                total_word_count:
                  type: integer
                  example: 20

    StudyActivity:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          example: "Vocabulary Quiz"
        thumbnail_url:
          type: string
          example: "https://example.com/thumbnail.jpg"
        description:
          type: string
          example: "Practice your vocabulary with flashcards"

    StudySession:
      type: object
      properties:
        id:
          type: integer
          example: 123
        activity_name:
          type: string
          example: "Vocabulary Quiz"
        group_name:
          type: string
          example: "Basic Greetings"
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        review_items_count:
          type: integer
          example: 20

    Pagination:
      type: object
      properties:
        current_page:
          type: integer
          example: 1
        total_pages:
          type: integer
          example: 5
        total_items:
          type: integer
          example: 100
        items_per_page:
          type: integer
          example: 100

paths:
  /dashboard/last_study_session:
    get:
      summary: Get most recent study session
      responses:
        '200':
          description: Latest study session info
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  group_id:
                    type: integer
                  created_at:
                    type: string
                    format: date-time
                  study_activity_id:
                    type: integer
                  group_name:
                    type: string

  /dashboard/study_progress:
    get:
      summary: Get study progress statistics
      responses:
        '200':
          description: Study progress stats
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_words_studied:
                    type: integer
                  total_available_words:
                    type: integer

  /dashboard/quick-stats:
    get:
      summary: Get quick overview statistics
      responses:
        '200':
          description: Quick statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_rate:
                    type: number
                    format: float
                  total_study_sessions:
                    type: integer
                  total_active_groups:
                    type: integer
                  study_streak_days:
                    type: integer

  /words:
    get:
      summary: Get paginated list of words with review statistics
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: Page number
        - name: sort_by
          in: query
          schema:
            type: string
            enum: [japanese, romaji, english, correct_count, wrong_count]
            default: japanese
          description: Field to sort by
        - name: order
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: asc
          description: Sort order
      responses:
        '200':
          description: Paginated list of words
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Word'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

  /words/{id}:
    get:
      summary: Get word details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Word details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WordDetail'

  /groups:
    get:
      summary: Get paginated list of word groups
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: Page number
        - name: sort_by
          in: query
          schema:
            type: string
            enum: [name, word_count]
            default: name
          description: Field to sort by
        - name: order
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: asc
          description: Sort order
      responses:
        '200':
          description: Paginated list of groups
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Group'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

  /groups/{id}:
    get:
      summary: Get group details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Group details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupDetail'

  /groups/{id}/words:
    get:
      summary: Get words in a group
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: Page number
      responses:
        '200':
          description: Paginated list of words in group
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Word'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

  /groups/{id}/study_sessions:
    get:
      summary: Get study sessions for a group
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: query
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Paginated list of study sessions
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/StudySession'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

  /study_activities/{id}:
    get:
      summary: Get study activity details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Study activity details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudyActivity'

  /study_activities/{id}/study_sessions:
    get:
      summary: Get study sessions for an activity
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: query
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Paginated list of study sessions
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/StudySession'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

  /study_sessions:
    get:
      summary: List all study sessions
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Paginated list of study sessions
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/StudySession'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

    post:
      summary: Create a new study session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - group_id
                - study_activity_id
              properties:
                group_id:
                  type: integer
                study_activity_id:
                  type: integer
      responses:
        '201':
          description: Created study session
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  group_id:
                    type: integer

  /study_sessions/{id}:
    get:
      summary: Get study session details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Study session details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudySession'

  /study_sessions/{id}/words:
    get:
      summary: Get words reviewed in a study session
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: query
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Paginated list of reviewed words
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Word'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

  /study_sessions/{session_id}/words/{word_id}/review:
    post:
      summary: Record a word review in a study session
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: integer
        - name: word_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - correct
              properties:
                correct:
                  type: boolean
      responses:
        '201':
          description: Created review record
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  word_id:
                    type: integer
                  study_session_id:
                    type: integer
                  correct:
                    type: boolean
                  created_at:
                    type: string
                    format: date-time

  /reset_history:
    post:
      summary: Reset study history
      responses:
        '200':
          description: History reset successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /full_reset:
    post:
      summary: Full system reset
      responses:
        '200':
          description: System reset successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string